######################################
# Run Super Linter against code base #
######################################

name: Super Linter

on: [push, pull_request]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
            
      - name: Lint Code Base
        uses: github/super-linter@master
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_JSCPD: false
          DEFAULT_BRANCH: master
          FILTER_REGEX_INCLUDE: .*\.(cpp|go|java|js|py|rb|swift)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
